{"metadata":{"timestamp":"2025-02-27T22:10:26Z"},"data":[{
      "cve": {
        "id": "CVE-2019-12219",
        "description": "An issue was discovered in libSDL2.a in Simple DirectMedia Layer (SDL) 2.0.9 when used in conjunction with libSDL2_image.a in SDL2_image 2.0.4. There is an invalid free error in the SDL function SDL_SetError_REAL at SDL_error.c.",
        "metadata": {
          "published_date": "2019-05-20T17:29:17.470",
          "last_modified_date": "2024-11-21T04:22:26.980",
          "confidence_level": "low",
          "severity": "high"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": false
        },
        "counts": {
          "public_exploit_count": 1
        },
        "epss": {
          "score": 0.02128,
          "percentile": 0.89117
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.0",
            "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
            "attack_vector": "NETWORK",
            "base_score": 8.80000019073486
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
            "attack_vector": "NETWORK",
            "base_score": 6.80000019073486
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://bugzilla.libsdl.org/show_bug.cgi?id=4625",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2019-05-20T05:00:00.000Z"
            }
          ]
        }
      }
    }]}