{
  "metadata": {
    "timestamp": "2025-02-25T08:14:55Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2022-48502",
        "description": "An issue was discovered in the Linux kernel before 6.2. The ntfs3 subsystem does not properly check for correctness during disk reads, leading to an out-of-bounds read in ntfs_set_ea in fs/ntfs3/xattr.c.",
        "metadata": {
          "published_date": "2023-05-31T20:15:10.303",
          "last_modified_date": "2024-11-21T07:33:27.053",
          "confidence_level": "low",
          "severity": "high"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": false
        },
        "counts": {
          "public_exploit_count": 1
        },
        "epss": {
          "score": 0.00057,
          "percentile": 0.2654
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H",
            "attack_vector": "LOCAL",
            "base_score": 7.09999990463257
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://syzkaller.appspot.com/bug?extid=8778f030156c6cd16d72",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2023-05-31T05:00:00.000Z"
            }
          ],
          "repositories": []
        }
      }
    }
  ]
}