{
  "metadata": {
    "timestamp": "2025-02-27T08:14:35Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2022-36126",
        "description": "An issue was discovered in Inductive Automation Ignition before 7.9.20 and 8.x before 8.1.17. The ScriptInvoke function allows remote attackers to execute arbitrary code by supplying a Python script.",
        "metadata": {
          "published": "",
          "last_modified": "",
          "confidence_level": "low",
          "severity": "high",
          "source": "",
          "status": ""
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": false
        },
        "metrics": [
          {
            "source": "cve@mitre.org",
            "type": "Secondary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
            "attack_vector": "NETWORK",
            "base_score": 7.19999980926514
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
            "attack_vector": "NETWORK",
            "base_score": 7.19999980926514
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://github.com/sourceincite/randy",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2022-07-16T05:00:00.000Z"
            }
          ],
          "repositories": null
        },
        "epss": {
          "score": 0.01879,
          "percentile": 0.88351
        },
        "counts": {
          "public_exploit_count": 1
        }
      }
    }
  ]
}