{"metadata":{"timestamp":"2025-02-27T22:10:26Z"},"data":[{
      "cve": {
        "id": "CVE-2021-3177",
        "description": "Python 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely.",
        "metadata": {
          "published_date": "2021-01-19T06:15:12.967",
          "last_modified_date": "2024-11-21T06:21:03.650",
          "confidence_level": "low",
          "severity": "critical"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": true
        },
        "counts": {
          "public_exploit_count": 1
        },
        "epss": {
          "score": 0.02506,
          "percentile": 0.90008
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "attack_vector": "NETWORK",
            "base_score": 9.80000019073486
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "attack_vector": "NETWORK",
            "base_score": 7.5
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://bugs.python.org/issue42938",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2021-01-19T05:00:00.000Z"
            }
          ]
        }
      }
    }]}